'use strict'

const {deepStrictEqual: eql} = require('assert')
const parseDataset = require('./lib/parse-dataset')

const descriptorA = {
	Select: [
		{
			Kind: 1,
			Depth: 0,
			Value: 'G0',
			GroupKeys: [{
				Source: {Entity: '0069_0700_Export', Property: 'Linie'},
				Calc: 'G0',
				IsSameAsSelect: true,
			}],
			Name: 'line',
		},
		{
			Kind: 1,
			Depth: 0,
			Value: 'G1',
			GroupKeys: [{
				Source: {Entity: '0069_0700_Export', Property: 'Richtung'},
				Calc: 'G1',
				IsSameAsSelect: true,
			}],
			Name: 'variant',
		},
		{
			Kind: 1,
			Depth: 0,
			Value: 'G2',
			GroupKeys: [{
				Source: {Entity: '0069_0700_Export', Property: 'Hst'},
				Calc: 'G2',
				IsSameAsSelect: true,
			}],
			Name: 'stop',
		},
		{
			Kind: 1,
			SecondaryDepth: 0,
			Value: 'G3',
			Format: '0',
			GroupKeys: [{
				Source: {Entity: '0069_0700_Export', Property: 'Stunde'},
				Calc: 'G3',
				IsSameAsSelect: true,
			}],
			Name: 'hour',
		},
		{
			Kind: 2,
			Value: 'M0',
			Format: '0.0',
			Name: 'occupancy',
		},
	],
	Expressions: {
		Primary: {
			Groupings: [
				{
					Keys: [{
						Source: {Entity: '0069_0700_Export', Property: 'Linie'},
						Select: 0,
					}, {
						Source: {Entity: '0069_0700_Export', Property: 'Richtung'},
						Select: 1,
					}, {
						Source: {Entity: '0069_0700_Export', Property: 'Hst'},
						Select: 2,
					}],
					Member: 'DM0',
				},
			],
		},
		Secondary: {
			Groupings: [{
				Keys: [{
					Source: {Entity: '0069_0700_Export', Property: 'Stunde'},
					Select: 3,
				}],
				Member: 'DM1',
			}]
		},
	},
	Limits: {
		Secondary: {
			Id: 'L0', Top: {Count: 100},
		},
	},
}

const datasetA = {
	N: 'DS0',
	IC: true,
	HAD: true,
	SH: [{
		DM1: [
			{G3: 6, S: [{N: 'G3', T: 4}]},
			{G3: 7},
			{G3: 8},
			{G3: 9},
			{G3: 10},
			{G3: 11},
			{G3: 12},
			{G3: 13},
			{G3: 14},
			{G3: 15},
			{G3: 16},
			{G3: 17},
			{G3: 18},
			{G3: 19},
			{G3: 20},
		],
	}],
	PH: [{
		DM0: [
			{
				S: [
					{N: 'G0', T: 1, DN: 'D0'},
					{N: 'G1', T: 1, DN: 'D1'},
					{N: 'G2', T: 1, DN: 'D2'},
				],
				C: [0, 0, 0],
				X: [
					{M0: 1, S: [{N: 'M0', T: 4}]},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {M0: 2},
					{R: 1}, {R: 1},
					{R: 1}, {M0: 1},
					{R: 1}, {R: 1},
				],
			},
			{
				C: [1],
				R: 3,
				X: [
					{M0: 2}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 3},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 2}, {R: 1},
					{M0: 3},
				],
			},
			{
				C: [2],
				R: 3,
				X: [
					{M0: 2}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 3},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 2},
					{M0: 3},
				],
			},
			{
				C: [3],
				R: 3,
				X: [
					{M0: 1}, {M0: 2},
					{M0: 1}, {R: 1},
					{M0: 2}, {R: 1},
					{R: 1},  {R: 1},
					{M0: 3}, {R: 1},
					{R: 1},  {R: 1},
					{M0: 2}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [4],
				R: 3,
				X: [
					{M0: 1}, {M0: 2},
					{M0: 1}, {R: 1},
					{R: 1},  {M0: 2},
					{R: 1},  {R: 1},
					{M0: 3}, {R: 1},
					{R: 1},  {R: 1},
					{M0: 2}, {M0: 1},
					{M0: 2},
				],
			},
			{
				C: [5],
				R: 3,
				X: [
					{M0: 1}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 2}, {R: 1},
					{M0: 3}, {R: 1},
					{R: 1},  {R: 1},
					{M0: 2}, {M0: 1},
					{M0: 2},
				],
			},
			{
				C: [6],
				R: 3,
				X: [
					{M0: 1}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 2}, {R: 1},
					{R: 1},  {M0: 3},
					{R: 1},  {R: 1},
					{M0: 2}, {M0: 1},
					{M0: 2},
				],
			},
			{
				C: [7],
				R: 3,
				X: [
					{M0: 0}, {M0: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 2},
					{R: 1},  {M0: 3},
					{M0: 2}, {R: 1},
					{R: 1},  {M0: 1},
					{M0: 2},
				],
			},
			{
				C: [8],
				R: 3,
				X: [
					{M0: 0}, {M0: 1},
					{M0: 0}, {R: 1},
					{M0: 1}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 2},
					{R: 1},  {M0: 1},
					{R: 1},  {R: 1},
					{R: 1},
				],
			},
			{
				C: [9],
				R: 3,
				X: [
					{M0: 0}, {M0: 1},
					{M0: 0}, {R: 1},
					{R: 1},  {M0: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},
				],
			},
			{
				C: [10],
				R: 3,
				X: [
					{M0: 0}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 1},
					{M0: 0}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},
				],
			},
			{
				C: [11],
				R: 3,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [12],
				R: 3,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [13],
				R: 3,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [14],
				R: 3,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [1, 15],
				R: 1,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [16],
				R: 3,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [17],
				R: 3,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [18],
				R: 3,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [19],
				R: 3,
				X: [
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 1},
					{M0: 0}, {R: 1},
					{M0: 1}, {R: 1},
					{R: 1},  {M0: 0},
					{R: 1},  {R: 1},
					{R: 1},
				],
			},
			{
				C: [20],
				R: 3,
				X: [
					{M0: 1}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 0},
					{M0: 1},
				],
			},
			{
				C: [21],
				R: 3,
				X: [
					{R: 1},  {R: 1},
					{M0: 2}, {M0: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 0},
					{M0: 1},
				],
			},
			{
				C: [22],
				R: 3,
				X: [
					{M0: 2}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 1},
					{R: 1},  {R: 1},
					{R: 1},
				],
			},
			{
				C: [23],
				R: 3,
				X: [
					{M0: 2}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 1},
					{R: 1},  {R: 1},
					{R: 1},
				],
			},
			{
				C: [24],
				R: 3,
				X: [
					{M0: 2}, {R: 1},
					{M0: 3}, {M0: 2},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [25],
				R: 3,
				X: [
					{M0: 2}, {R: 1},
					{M0: 3}, {M0: 2},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 3},
					{R: 1},  {M0: 2},
					{M0: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [26],
				R: 3,
				X: [
					{M0: 2}, {R: 1},
					{M0: 3}, {M0: 2},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 3},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 2},
					{M0: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [27],
				R: 3,
				X: [
					{M0: 2}, {R: 1},
					{M0: 3}, {M0: 2},
					{R: 1},  {M0: 3},
					{M0: 2}, {M0: 3},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 2},
					{R: 1},  {M0: 1},
					{M0: 2},
				],
			},
			{
				C: [28],
				R: 3,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {M0: 3},
					{R: 1}, {R: 1},
					{R: 1}, {M0: 2},
					{R: 1}, {M0: 1},
					{R: 1},
				],
			},
			{
				C: [29],
				R: 3,
				X: [
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 2},
					{M0: 1}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 0},
					{M0: 1},
				],
			},
			{
				C: [1, 2, 30],
				X: [
					{M0: 0}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},
				],
			},
			{
				C: [31],
				R: 3,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [32],
				R: 3,
				X: [
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 1}, {R: 1},
					{R: 1},  {M0: 0},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},
				],
			},
			{
				C: [33],
				R: 3,
				X: [
					{R: 1}, {M0: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {M0: 0},
					{R: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [34],
				R: 3,
				X: [
					{M0: 1}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 0},
					{R: 1},
				],
			},
			{
				C: [35],
				R: 3,
				X: [
					{M0: 2}, {M0: 1},
					{R: 1},  {M0: 2},
					{M0: 1}, {R: 1},
					{R: 1},  {R: 1},
					{M0: 2}, {M0: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},
				],
			},
			{
				C: [36],
				R: 3,
				X: [
					{M0: 2}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 1},
					{R: 1},  {R: 1},
					{R: 1},
				],
			},
			{
				C: [37],
				R: 3,
				X: [
					{M0: 3}, {M0: 2},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [38],
				R: 3,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {M0: 0},
					{R: 1},
				],
			},
			{
				C: [39],
				R: 3,
				X: [
					{M0: 2}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 1},
					{R: 1},  {M0: 2},
					{R: 1},  {M0: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 0},
					{M0: 1},
				],
			},
			{
				C: [40],
				R: 3,
				X: [
					{R: 1},  {M0: 2},
					{M0: 1}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 0},
				],
			},
			{
				C: [3, 41],
				R: 1,
				X: [
					{M0: 1}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 2}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 1},
					{R: 1},
				],
			},
			{
				C: [42],
				R: 3,
				X: [
					{M0: 0}, {R: 1},
					{M0: 1}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 2},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 1},
					{R: 1},
				],
			},
			{
				C: [43],
				R: 3,
				X: [
					{M0: 0}, {R: 1},
					{R: 1},  {R: 1},
					{M0: 1}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 0},
				],
			},
			{
				C: [44],
				R: 3,
				X: [
					{R: 1},  {M0: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 2},
					{R: 1},  {M0: 3},
					{R: 1},  {M0: 2},
					{M0: 3}, {M0: 2},
					{M0: 1},
				],
			},
			{
				C: [45],
				R: 3,
				X: [
					{M0: 0}, {R: 1},
					{M0: 1}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 2}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 1},
				],
			},
			{
				C: [46],
				R: 3,
				X: [
					{M0: 0}, {R: 1},
					{R: 1},  {R: 1},
					{M0: 1}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 2}, {M0: 1},
					{M0: 2}, {M0: 1},
					{R: 1},
				],
			},
			{
				C: [47],
				R: 3,
				X: [
					{M0: 0}, {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {M0: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 0},
				],
			},
			{
				C: [48],
				R: 3,
				X: [
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 1}, {M0: 0},
					{R: 1},  {M0: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 0},
				],
			},
			{
				C: [49],
				R: 3,
				X: [
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{R: 1},  {R: 1},
					{M0: 1}, {M0: 0},
					{M0: 1}, {R: 1},
					{M0: 0},
				],
			},
			{
				C: [50],
				R: 3,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [51],
				R: 3,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1},
				],
			},
			{
				C: [52],
				R: 3,
				X: [
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1}, {R: 1},
					{R: 1},
				],
			},
		],
	}],
	ValueDicts: {
		D0: ['M32', 'X21'],
		D1: [
			'(H) S+U Rathaus Spandau > Heidebergplan',
			'(R) Heidebergplan > S+U Rathaus Spandau',
			'(H) Quickborner Str. > U Jakob-Kaiser-Platz',
			'(R) U Jakob-Kaiser-Platz > Quickborner Str.',
		],
		D2: [
			'(01) S+U Rathaus Spandau',
			'(02) Brunsbütteler D./Ruhlebener Str.',
			'(03) Elsflether Weg',
			'(04) Grünhofer Weg',
			'(05) Nauener Str.',
			'(06) Päwesiner Weg',
			'(07) Egelpfuhlstr.',
			'(08) Harburger Weg',
			'(09) Magistratsweg/Brunsbütteler D.',
			'(10) Louise-Schroeder-Siedlung',
			'(11) Zweiwinkelweg',
			'(12) Brunsbütteler D./Nennhauser D.',
			'(13) Bahnhof Staaken',
			'(14) Finkenkruger Weg',
			'(15) Am Kurzen Weg',
			'(01) Heidebergplan',
			'(02) Am Kurzen Weg',
			'(03) Finkenkruger Weg',
			'(04) Bahnhof Staaken',
			'(05) Brunsbütteler D./Nennhauser D.',
			'(06) Zweiwinkelweg',
			'(07) Louise-Schroeder-Siedlung',
			'(08) Magistratsweg/Brunsbütteler D.',
			'(09) Harburger Weg',
			'(10) Egelpfuhlstr.',
			'(11) Päwesiner Weg',
			'(12) Nauener Str.',
			'(13) Grünhofer Weg',
			'(14) Elsflether Weg',
			'(15) Brunsbütteler D./Ruhlebener Str.',
			'(01) Quickborner Str.',
			'(02) Zerpenschleuser Ring',
			'(03) Quickborner/Treuenbrietzener Str',
			'(04) Gandenitzer Weg',
			'(05) Packereigraben',
			'(06) Wilhelmsruher D/Treuenbrietzener',
			'(07) Märkisches Zentrum',
			'(08) Schorfheidestr./Eichhorster Weg',
			'(09) S+U Wittenau [Bus]',
			'(10) S+U Karl-Bonhoeffer-Nervenklinik',
			'(11) U Kurt-Schumacher-Platz',
			'(01) U Jakob-Kaiser-Platz',
			'(02) U Kurt-Schumacher-Platz',
			'(03) S+U Karl-Bonhoeffer-Nervenklinik',
			'(04) S+U Wittenau [Bus]',
			'(05) Schorfheidestr./Eichhorster Weg',
			'(06) Märkisches Zentrum',
			'(07) Wilhelmsruher D/Treuenbrietzener',
			'(08) Packereigraben',
			'(09) Gandenitzer Weg',
			'(10) Quickborner/Treuenbrietzener Str',
			'(11) Zerpenschleuser Ring',
			'(12) Quickborner Str.',
		],
	},
}

eql(parseDataset(datasetA, descriptorA), [
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(01) S+U Rathaus Spandau',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(02) Brunsbütteler D./Ruhlebener Str.',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 3})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(03) Elsflether Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 3})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(04) Grünhofer Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 7, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 8, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(05) Nauener Str.',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 7, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 8, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 2})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(06) Päwesiner Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 2})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(07) Egelpfuhlstr.',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 2})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(08) Harburger Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 7, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 16, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 2})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(09) Magistratsweg/Brunsbütteler D.',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 7, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 8, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(10) Louise-Schroeder-Siedlung',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 7, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 8, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(11) Zweiwinkelweg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 16, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(12) Brunsbütteler D./Nennhauser D.',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(13) Bahnhof Staaken',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(14) Finkenkruger Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(H) S+U Rathaus Spandau > Heidebergplan',
			stop: '(15) Am Kurzen Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(01) Heidebergplan',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(02) Am Kurzen Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(03) Finkenkruger Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(04) Bahnhof Staaken',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(05) Brunsbütteler D./Nennhauser D.',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 12, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(06) Zweiwinkelweg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 1})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(07) Louise-Schroeder-Siedlung',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 9, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 1})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(08) Magistratsweg/Brunsbütteler D.',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(09) Harburger Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(10) Egelpfuhlstr.',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 9, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(11) Päwesiner Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 9, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 18, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(12) Nauener Str.',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 9, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 18, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(13) Grünhofer Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 9, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 12, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 13, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 2})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(14) Elsflether Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'M32',
			variant: '(R) Heidebergplan > S+U Rathaus Spandau',
			stop: '(15) Brunsbütteler D./Ruhlebener Str.',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 14, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 1})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(H) Quickborner Str. > U Jakob-Kaiser-Platz',
			stop: '(01) Quickborner Str.',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(H) Quickborner Str. > U Jakob-Kaiser-Platz',
			stop: '(02) Zerpenschleuser Ring',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(H) Quickborner Str. > U Jakob-Kaiser-Platz',
			stop: '(03) Quickborner/Treuenbrietzener Str',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(H) Quickborner Str. > U Jakob-Kaiser-Platz',
			stop: '(04) Gandenitzer Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(H) Quickborner Str. > U Jakob-Kaiser-Platz',
			stop: '(05) Packereigraben',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(H) Quickborner Str. > U Jakob-Kaiser-Platz',
			stop: '(06) Wilhelmsruher D/Treuenbrietzener',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 7, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 10, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 15, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(H) Quickborner Str. > U Jakob-Kaiser-Platz',
			stop: '(07) Märkisches Zentrum',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(H) Quickborner Str. > U Jakob-Kaiser-Platz',
			stop: '(08) Schorfheidestr./Eichhorster Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 7, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(H) Quickborner Str. > U Jakob-Kaiser-Platz',
			stop: '(09) S+U Wittenau [Bus]',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(H) Quickborner Str. > U Jakob-Kaiser-Platz',
			stop: '(10) S+U Karl-Bonhoeffer-Nervenklinik',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 1})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(H) Quickborner Str. > U Jakob-Kaiser-Platz',
			stop: '(11) U Kurt-Schumacher-Platz',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 8, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 0})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(R) U Jakob-Kaiser-Platz > Quickborner Str.',
			stop: '(01) U Jakob-Kaiser-Platz',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(R) U Jakob-Kaiser-Platz > Quickborner Str.',
			stop: '(02) U Kurt-Schumacher-Platz',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(R) U Jakob-Kaiser-Platz > Quickborner Str.',
			stop: '(03) S+U Karl-Bonhoeffer-Nervenklinik',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 0})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(R) U Jakob-Kaiser-Platz > Quickborner Str.',
			stop: '(04) S+U Wittenau [Bus]',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 18, occupancy: 3})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 1})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(R) U Jakob-Kaiser-Platz > Quickborner Str.',
			stop: '(05) Schorfheidestr./Eichhorster Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 1})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(R) U Jakob-Kaiser-Platz > Quickborner Str.',
			stop: '(06) Märkisches Zentrum',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 17, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 18, occupancy: 2})},
			{data: Object.assign(Object.create(null), {hour: 19, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(R) U Jakob-Kaiser-Platz > Quickborner Str.',
			stop: '(07) Wilhelmsruher D/Treuenbrietzener',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 0})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(R) U Jakob-Kaiser-Platz > Quickborner Str.',
			stop: '(08) Packereigraben',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 13, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 0})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(R) U Jakob-Kaiser-Platz > Quickborner Str.',
			stop: '(09) Gandenitzer Weg',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 17, occupancy: 0})},
			{data: Object.assign(Object.create(null), {hour: 18, occupancy: 1})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20, occupancy: 0})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(R) U Jakob-Kaiser-Platz > Quickborner Str.',
			stop: '(10) Quickborner/Treuenbrietzener Str',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(R) U Jakob-Kaiser-Platz > Quickborner Str.',
			stop: '(11) Zerpenschleuser Ring',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
	{
		data: Object.assign(Object.create(null), {
			line: 'X21',
			variant: '(R) U Jakob-Kaiser-Platz > Quickborner Str.',
			stop: '(12) Quickborner Str.',
		}),
		children: [
			{data: Object.assign(Object.create(null), {hour: 6})},
			{data: Object.assign(Object.create(null), {hour: 7})},
			{data: Object.assign(Object.create(null), {hour: 8})},
			{data: Object.assign(Object.create(null), {hour: 9})},
			{data: Object.assign(Object.create(null), {hour: 10})},
			{data: Object.assign(Object.create(null), {hour: 11})},
			{data: Object.assign(Object.create(null), {hour: 12})},
			{data: Object.assign(Object.create(null), {hour: 13})},
			{data: Object.assign(Object.create(null), {hour: 14})},
			{data: Object.assign(Object.create(null), {hour: 15})},
			{data: Object.assign(Object.create(null), {hour: 16})},
			{data: Object.assign(Object.create(null), {hour: 17})},
			{data: Object.assign(Object.create(null), {hour: 18})},
			{data: Object.assign(Object.create(null), {hour: 19})},
			{data: Object.assign(Object.create(null), {hour: 20})},
		],
	},
])

// todo: test scrapeOccupancies
